<?php

return [

    /*
    |--------------------------------------------------------------------------
    | PDF export branding (reports & account statements)
    |--------------------------------------------------------------------------
    |
    | Placeholders for footer_line: {REPORT_NAME}, {PRODUCT_NAME}, {WEBSITE}, {PHONE}
    | {WEBSITE} and {PHONE} are rendered as clickable links in PDF exports.
    |
    */

    'pdf' => [
        'footer_line' => '{REPORT_NAME} generated by {PRODUCT_NAME}, {WEBSITE} {PHONE}',

        'product_name' => 'theFoodPOS',
        'website' => 'thefoodpos.com',
        'website_url' => 'https://thefoodpos.com',
        'phones' => [
            ['label' => '03065918097', 'tel' => '03065918097'],
            ['label' => '0312 7032292', 'tel' => '03127032292'],
        ],

        'watermark' => [
            'enabled' => true,
            'logo' => 'images/thefoodpos-logo.png',
            'opacity' => 0.12,
            'width' => 420,
        ],
    ],

];
